// <auto-generated />
using DovizKurlari.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DovizKurlari.Migrations
{
    [DbContext(typeof(MyApplicationContext))]
    [Migration("20210926192732_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DovizKurlari.Models.InternetKurlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CaprazKur")
                        .HasColumnType("integer");

                    b.Property<string>("Doviz")
                        .HasColumnType("text");

                    b.Property<int>("DovizAlis")
                        .HasColumnType("integer");

                    b.Property<int>("DovizKodu")
                        .HasColumnType("integer");

                    b.Property<int>("DovizSatis")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("InternetKurlari");
                });

            modelBuilder.Entity("DovizKurlari.Models.MarbasPariteleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AlisParitesi")
                        .HasColumnType("integer");

                    b.Property<string>("PariteCinsi")
                        .HasColumnType("text");

                    b.Property<int>("SatisParitesi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MarbasPariteleri");
                });

            modelBuilder.Entity("DovizKurlari.Models.SerbestKurlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CaprazKur")
                        .HasColumnType("integer");

                    b.Property<string>("Doviz")
                        .HasColumnType("text");

                    b.Property<int>("DovizAlis")
                        .HasColumnType("integer");

                    b.Property<int>("DovizKodu")
                        .HasColumnType("integer");

                    b.Property<int>("DovizSatis")
                        .HasColumnType("integer");

                    b.Property<int>("EfektifAlis")
                        .HasColumnType("integer");

                    b.Property<int>("EfektifSatis")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SerbestKurlar");
                });
#pragma warning restore 612, 618
        }
    }
}
